version: "3.6"

services:
  api-image:
    container_name: app-image
    build:
      context: ./app
    volumes:
      - $HOME/.aws/:/root/.aws/
    ports:
      - "9000:8080"
    env_file:
      - .env
